export { default as AlignJustify } from "./AlignJustify";
export { default as ArrowLeft } from "./ArrowLeft";
export { default as ArrowRightMedium } from "./ArrowRightMedium";
export { default as ArrowRightRegular } from "./ArrowRightRegular";
export { default as Arrow } from "./Arrow";
export { default as Cancel } from "./Cancel";
export { default as Insta } from "./Insta";
export { default as Telegram } from "./Telegram";
export { default as Whatsapp } from "./Whatsapp";
